server:
  max-http-header-size: 8KB
  tomcat:
    max-swallow-size: 1MB

spring:
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: user
  # uncomment the line below
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/spring_db?createDatabaseIfNotExist=true&serverTimezone=UTC
  # uncomment the line below when use in localhost
#    url: jdbc:mysql://localhost:3306/spring_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: nova
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

bucket4j:
  enabled: true
  filters:
    - cache-name: rateLimit
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 50
              time: 50
              unit: seconds