version: '3.4'
services:
  db:
    image: mysql:8.0.29-oracle
    container_name: mysql_8_29_v1
    command: mysqld --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_DATABASE=spring_db
      - MYSQL_PASSWORD=nova
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - bookchallenge-network
  rest_bookchallenge:
    image: maven:3.8-openjdk-17-slim
    restart: always
    build: ./bookchallenge
    working_dir: /bookchallenge
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
    volumes:
      - ./bookchallenge:/bookchallenge
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080" 
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - bookchallenge-network
networks:
  bookchallenge-network:
    driver: bridge
        


    # image: perycles/spring_db
    # command: --innodb-use-native-aio=0
    # container_name: mysql_8_1_v2
    # restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # volumes: 
    #   - mysql_db:/var/lib/mysql
    # environment:
    #   TZ: America/Sao_Paulo
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: spring_db
    #   MYSQL_PASSWORD: nova
    #   MYSQL_USER: user
    # ports:
    #   - "3308:3306"